name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Lint, Test, Build
    runs-on: ubuntu-latest

    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333
        options: >-
          --health-cmd="curl --fail http://localhost:6333 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black flake8

      - name: Lint with flake8
        run: |
          flake8 . --exclude=venv,.venv,.git,__pycache__,data --max-line-length=100

      - name: Format check with black
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest tests/

      - name: Build Docker image
        run: |
          docker build -t warhammer-api .
